name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Request Vercel deploy
        run: curl ${{ secrets.DOCS_SITE_DEPLOY_HOOK }}
