name: Proofread

on: [push, pull_request]

jobs:
  proofread:
    name: Proofread
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: place-labs/orthograph-err@master
